when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        register_error_listener: true
        register_error_handler: true
        options:
            environment: '%kernel.environment%'
            release: '%env(APP_VERSION)%'
            traces_sample_rate: 0.2
            profiles_sample_rate: 0.1
            send_default_pii: false
        tracing:
            enabled: true
            dbal:
                enabled: true
            cache:
                enabled: true
            twig:
                enabled: false
            http_client:
                enabled: false

when@dev:
    sentry:
        dsn: ''
